### ISSUE TITLE
<DELETE> key not working

### ISSUE THREAD

**Issue by rsteelink** [totaljs/flowstream#10]
Hello.

When editing the configuration of a component you cannot use the DELETE key to delete characters.
Furthermore, created components can't be deleted by using the DELETE key in certain situations.

Steps to reproduce:
- Create new flowstream
- Insert input component
- Enter a character in the input name in the configuration
- Try to delete the character
- Close component and hit Apply
- Close the flowstream
- Open the flowstream
- Try to delete the component

Deleting the component is fixed when you edit the component

**Comment by petersirka** [comment]
Fixed https://github.com/totaljs/flowstreamdesigner/commit/21d75c508119082506c8ffb6c644dec521a62824.

**Comment by petersirka** [comment]
BTW: flowstreamdesigner.totaljs.com **is updated**.
