### ISSUE TITLE
Publish component in flow loses setttings to input on importing flow

### ISSUE THREAD

**Issue by ponsoc** [totaljs/flowstream#13]
Steps to reproduce.

Great a flow with an input and publish component. Set the configuration of the publish component to the input. Export the flow and then remove it. Now reimport the flow. The configuration of the publish component is lost.

**Comment by petersirka** [comment]
@roelvanegmond it's not a bug. The `publish` component stores FlowStream identifier + input instance identifier.... So if you remove the FlowStream, then the FlowStream identifier doesn't exist and therefore is removed.

Currently, I can't imagine a solution for it. Maybe create another similar component to the `publish` that will work in the scope of the current FlowStream.
