### ISSUE TITLE
Environment variables for config

### ISSUE THREAD

**Issue by wildone** [totaljs/flowstream#18]
Hi @petersirka!

First of all thank you and the team behind this awesome project, we are in the process learning and adopting your tools into our project! You guys are awesome!

I am looking for any docs on command line parameters that I can pass all config setting to the app when starting it?

**Comment by petersirka** [comment]
Hi @wildone, thank you a lot.

We recommend updating `/config` file (it's part of every Total.js app). If you want to change something via user environment variables, then you can easily map config values:

```
name           (env)   : APP_NAME
database       (env)   : CONN_STRING
```

Or if you want to change something manually then use [`LOACONFIG()`](https://docs.totaljs.com/total4/407ff001jy51c/#a6923001br51c) method.

**Comment by wildone** [comment]
@petersirka ok that works thanks, have you seen https://github.com/motdotla/dotenv?

**Comment by petersirka** [comment]
Total.js has implemented reading of `.env` file:

- [Documentation](https://docs.totaljs.com/total4/7bf9f001fx51c/)
- `/your-app/.env` for development/production
- `/your-app/.env-debug` for development
- `/your-app/.env-release` for production

__Parsed data are attached to the__ `process.env` __variable.__

- a simple parser [`String.parseENV()`](https://docs.totaljs.com/total4/4047e003ik51c/#4b625001rr51c)

**Comment by wildone** [comment]
thank you!
