### ISSUE TITLE
Saving issues

### ISSUE THREAD

**Issue by ponsoc** [totaljs/flowstream#4]
Hi Peter,

From time to time we have some issues with saving changes. For some reason they are not properly saved.
This can be edits of flow settings, like the name, icon our group. But also components in a flow that aren't there any more after rebooting or connections between components. I have attached a video to show you.

[

https://user-images.githubusercontent.com/36486184/130914107-9dcfc5d8-f04c-48a3-a95c-85f0089cd455.mp4

](url)

**Comment by petersirka** [comment]
Can you export your Flow? If yes, you can send me it via Telegram. I think that the problem can be in the design, and I need to debug saving.

**Comment by petersirka** [comment]
Does it work?

**Comment by ponsoc** [comment]
yes
