### ISSUE TITLE
Unexpected behaviors in instance.message_<INPUT_NAME>(message) function

### ISSUE THREAD

**Issue by AlejandroSotoCastro** [totaljs/flowstream#6]
Hi Peter,

while using the  instance.message_<INPUT_NAME>(message) function we've notice a few things:

```javascript
	instance.message_buffer = function($) {
		let data = $.data;
		instance.send("output", data)
	}
```
- It seems like the input parameter to use in the function definition  is not <INPUT_NAME>, but <INPUT_ID>
- When data is sent to that input, the message_buffer function is triggered but no data is available.
- Trying to access $.data throws the following error:

![image](https://user-images.githubusercontent.com/58389626/131097002-280f7262-4562-45d0-ae0a-15caf7a7948e.png)

I leave you here screenshot and link of the documentation I'm looking at

![image](https://user-images.githubusercontent.com/58389626/131095074-25533d74-b198-426c-9240-78a31fc7af53.png)

https://docs.totaljs.com/total4/5aed2001pj51c/#8886d001gs51c

**Comment by petersirka** [comment]
Hi @AlejandroSotoCastro.
Please, can you test your FlowStream with the latest beta version of the Total.js framework?

- `npm install total4@beta`
- and then send me the output

Thank you!

**Comment by AlejandroSotoCastro** [comment]
Hi, pretty much the same error

```
FlowError TypeError: Cannot read property 'instance' of null
    at Object.FP.ontrigger [as send] (C:\Users\AlejandroSotoCastro\Desktop\Projects\GitHub\xill4-engine\node_modules\total4\flowstream.js:820:38)
    at Object.instance.message_buffer (eval at FP.add (C:\Users\AlejandroSotoCastro\Desktop\Projects\GitHub\xill4-engine\node_modules\total4\flowstream.js:1374:9), <anonymous>:76:12)
    at Immediate.sendmessage [as _onImmediate] (C:\Users\AlejandroSotoCastro\Desktop\Projects\GitHub\xill4-engine\node_modules\total4\flowstream.js:1197:34)
    at processImmediate (internal/timers.js:466:21) instance_message
```

**Comment by petersirka** [comment]
Yes, there was a bug. Can you test it again? I have released a new beta version.

- `npm install total4@beta`

**Comment by AlejandroSotoCastro** [comment]
It's not throwing the error, but I don't get any data either.
Is my syntax correct ?

```javascript
instance.message_buffer = function($) {
      let data = $.data;
      instance.send("output",data)
	}
```

If instead of sending data I send a string I can see it on the output

**Comment by petersirka** [comment]
I have fixed my fix :-D. There was a hidden bug.

- Please try reinstall beta version: `npm install total4@beta`

**Comment by AlejandroSotoCastro** [comment]
I still experience the same problem

**Comment by petersirka** [comment]
Can you send me your FlowStream app? My test works, so I need to test it on your example.
Thank you

**Comment by petersirka** [comment]
Does it work?

**Comment by AlejandroSotoCastro** [comment]
That version of the beta still breaks my setup and I haven't had time to fix it

**Comment by AlejandroSotoCastro** [comment]
Hi Peter, Bob also tried out this version of the beta an he got  the same error I do, when running the engine after updating it crashes looking for the fs package.
Can't spend more time on this today, but I'll try to answer you tomorrow.

**Comment by petersirka** [comment]
I have tested it again and it works. Here is my test FlowStream design:

- you need to have installed Total.js 4 beta
- [inputs.json.zip](https://github.com/totaljs/flowstream/files/7083352/inputs.json.zip)

**Comment by AlejandroSotoCastro** [comment]
Morning, we've checked and we all get the same problem:
![image](https://user-images.githubusercontent.com/58389626/131643211-866f14e7-6bd1-4132-8174-ae7ef4636c20.png)

could it be related with the flowstream\/node_modules/fs ? the \/

**Comment by petersirka** [comment]
Yes, I forgot to internal Node.js modules. I have fixed it; please reinstall Total.js 4 beta and let me know.

```bash
npm install total4@beta
```

**Comment by AlejandroSotoCastro** [comment]
Working! Still need to try out the original problem in this version though!

**Comment by AlejandroSotoCastro** [comment]
Good morning,
I've tried this and it works. Let me know if this is the correct instance and if so I think we can close this issue.
![image](https://user-images.githubusercontent.com/58389626/131793476-dd080357-2031-4886-9633-dfa14b5e4b81.png)

**Comment by petersirka** [comment]
@AlejandroSotoCastro this isn't correct usage.

Better is to use:

```js
instance.message = function($) {

    // $.index {String} means input name

    if ($.index === 'buffer') {
        // do something with a buffer
        $.send('output', YOUR_DATA);
    } else {
        $.destroy();
    }
    
};
```

or define `message_<INPUT_NAME>` for each input:

```js
instance.message_buffer = function($) {
    $.send('output1', YOUR_DATA);
};

instance.message_plain = function($) {
    $.send('output1', YOUR_DATA);
};
```

You can't destroy the message after `$.send()` because the message will be destroyed in the next instance. However, if the `$.send()` method doesn't find any output, it automatically destroys the message.

**Comment by AlejandroSotoCastro** [comment]
allright! Thanks

**Comment by petersirka** [comment]
BTW: I have extended __message instance__ `$` by adding `$.input {String}` - alias for `$.index`. It will be more readable.

**Comment by AlejandroSotoCastro** [comment]
I agree, it is more readable.
Shall I close the issue then?

**Comment by petersirka** [comment]
Of course. I'll release a new beta version today.

**Comment by AlejandroSotoCastro** [comment]
Perfect
