### ISSUE TITLE
Connection between components disappearing in flow

### ISSUE THREAD

**Issue by AlejandroSotoCastro** [totaljs/flowstream#9]
Connections between components disappear when opening reading the database.json.
To reproduce:

1. download flowstream version from telegram (it has some additional NPM packages installed).
2. download the attached database.json. and put it in to the flowstream folder.
3. run flow stream.

You will see that the database.json will be changed on the moment of running the engine and if you look at the flow, connections will be missing.

If you then run a diff between the database.json you downloaded and the one in the flowstream folder. You will see the the connection keys between components have changed.
[database.zip](https://github.com/totaljs/flowstream/files/7259245/database.zip)

**Comment by petersirka** [comment]
Fixed https://github.com/totaljs/flowstream/commit/f3f13b9693370ffba331e8be5327fcf7ec81d84b.
